=== folio-org/deprecated-mod-metadata/doc/api/inventory/schema/item.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "instanceId": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "barcode": {
      "type": "string"
    },
    "status": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "materialType": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "location": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  "required": [
    "id",
    "title",
    "instanceId"
  ]
}

=== folio-org/deprecated-mod-metadata/inventory/doc/api/inventory/examples/item_get.json
{
  "id": "0b96a642-5e7f-452d-9cae-9cee66c9a892",
  "instanceId": "cf23adf0-61ba-4887-bf82-956c4aae2260",
  "title": "Uprooted",
  "barcode": "645398607547",
  "status": {
    "name" : "Available"
  },
  "materialType": {
    "id": "fcf3d3dc-b27f-4ce4-a530-542ea53cacb5",
    "name": "Book"
  },
  "location": {
    "name": "Main Library"
  }
}
