=== folio-org/deprecated-mod-metadata/inventory-storage/ramls/schema/item.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "instanceId": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "barcode": {
      "type": "string"
    },
    "status": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "materialTypeId": {
      "type": "string"
    },
    "loanTypeId": {
      "type": "string"
    },
    "location": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "instanceId",
    "barcode"
  ]
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/interesting-times-item.json
{
  "id": "bb5a6689-c008-4c96-8f8f-b666850ee12d",
  "instanceId": "a89eccf0-57a6-495e-898d-32b9b2210f2f",
  "title": "Interesting Times",
  "barcode": "326547658598",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "status": {
    "name": "Available"
  },
  "location": {
    "name": "Annex Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/temeraire2-item.json
{
  "id": "23fdb0bc-ab58-442a-b326-577a96204487",
  "instanceId": "cf23adf0-61ba-4887-bf82-956c4aae2260",
  "title": "Temeraire",
  "barcode": "653285216743",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "status": {
    "name": "Checked Out"
  },
  "location": {
    "name": "Annex Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/temeraire-item.json
{
  "id": "0b96a642-5e7f-452d-9cae-9cee66c9a892",
  "instanceId": "cf23adf0-61ba-4887-bf82-956c4aae2260",
  "title": "Temeraire",
  "barcode": "645398607547",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "status": {
    "name": "Available"
  },
  "location": {
    "name": "Main Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/nod-item.json
{
  "id": "23f2c8e1-bd5d-4f27-9398-a688c998808a",
  "instanceId": "6506b79b-7702-48b2-9774-a1c538fdd34e",
  "title": "Nod",
  "barcode": "697685458679",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2e48e713-17f3-7c13-09f8-23845bb210a4",
  "status": {
    "name": "Checked Out"
  },
  "location": {
    "name": "Main Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/bridget-jones-baby-item.json
{
  "id": "1b6d3338-186e-4e35-9e75-1b886b0da53e",
  "instanceId": "7fbd5d84-62d1-44c6-9c45-6cb173998bbd",
  "title": "Bridget Jones's Baby",
  "barcode": "453987605438",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "status": {
    "name": "Checked Out"
  },
  "location": {
    "name": "Main Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/sample-data/items/girl-on-the-train-item.json
{
  "id": "459afaba-5b39-468d-9072-eb1685e0ddf4",
  "instanceId": "f31a36de-fcf8-44f9-87ef-a55d06ad21ae",
  "title": "The Girl on the Train",
  "barcode": "765475420716",
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "status": {
    "name": "Available"
  },
  "location": {
    "name": "Annex Library"
  }
}

=== folio-org/deprecated-mod-metadata/inventory-storage/ramls/examples/item_get.json
{
  "id": "0b96a642-5e7f-452d-9cae-9cee66c9a892",
  "instanceId": "cf23adf0-61ba-4887-bf82-956c4aae2260",
  "title": "Uprooted",
  "barcode": "645398607547",
  "status": {
    "name": "Available"
  },
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "loanTypeId": "2b94c631-fca9-a892-c730-03ee529ffe27",
  "location": {
    "name": "Main Library"
  }
}
